const regionList = [
    {
        name: "shanghai",
        text: "上海",
        lon: 121.483531,
        lat: 31.271758,
        children: [
            {
                name: "luxunPark",
                text: "鲁迅公园",
                descript: "怀念与你的不期而遇，自从在鲁迅公园见到你，你的笑容便刻在了我的脑海里，挥之不去",
                lon: 121.483531,
                lat: 31.271758,
            },
            {
                name: "syLife",
                text: "上外生活区",
                descript: "喜欢体育会路两旁的梧桐树，给炎热的夏天带来丝丝清凉；更喜欢跟你一起牵手漫步，无论冬夏，如沐春风",
                lon: 121.485414,
                lat: 31.278241,
            },
            {
                name: "syRiverside",
                text: "上外河岸",
                descript: "闹市中的一隅，与你对酒当歌，波光粼粼的小河代表着我对你的爱永不干涸",
                lon: 121.482542,
                lat: 31.277711,
            },
            {
                name: "quyangPark",
                text: "曲阳公园",
                descript: "曲径通幽，阳关三叠，想公园再大一些，能让我们多走一会儿",
                lon: 121.485585,
                lat: 31.286945,
            },
            {
                name: "hkFootBallStation",
                text: "虹口足球场",
                descript: "为什么我不想周日来这里，因为这里见证了太多分离，我想让我们到过的每一个地方，回忆起来都是开心的",
                lon: 121.480652,
                lat: 31.271136,
            },
            {
                name: "wujiaochang",
                text: "五角场",
                descript: "那天不光你怂，我也怂了，好在我们玩小游戏玩的挺开心，不虚此行，哦这里的饭也很好吃",
                lon: 121.515633,
                lat: 31.299927,
            },
            {
                name: "hanguoStreet",
                text: "韩国街",
                descript: "风车、麦田、炸鸡、烤肉、拉面、泡菜、啤酒... 我还想要小视频",
                lon: 121.373334,
                lat: 31.170158,
            },
            {
                name: "shSouthStation",
                text: "上海南站",
                descript: "每次都想在南站广场多坐一会儿，每次都想在地铁口多看你一眼",
                lon: 121.427558,
                lat: 31.154078,
            },
            {
                name: "zhujiajiao",
                text: "朱家角",
                descript: "疫情之下，能称得上说走就走的旅行，泛舟游于江南古镇，赏亭台楼阁，看落日余晖",
                lon: 121.055018,
                lat: 31.110211,
            },
            {
                name: "yulanyayuan",
                text: "御澜雅苑",
                descript: "我们在这里过生日、跨年、亲亲、抱抱……，这里有我们生活的点点滴滴，让我在偌大的城市中找到家的温暖",
                lon: 121.147039,
                lat: 31.154067,
            },
        ],
    },
    {
        name: "changsha",
        text: "长沙",
        lon: 112.968614,
        lat: 28.189923,
        children: [
            {
                name: "xjWestRoad",
                text: "湘江西路",
                descript: "首次自驾之旅，漫步湘江岸边，最美的风景不过是你眼中倒映下的那片星空",
                lon: 112.968614,
                lat: 28.189923,
            },
            {
                name: "chayanyuese",
                text: "茶颜悦色",
                descript: "停电也抵挡不住两名吃货的脚步，咦？你看，夕阳！为什么我们遇到的夕阳都那么美？",
                lon: 112.987058,
                lat: 28.182293,
            },
        ],
    },
    {
        name: "jianli",
        text: "监利",
        lon: 112.906496,
        lat: 29.847302,
        children: [
            {
                name: "busStation",
                text: "汽车站",
                descript: "2021年2月20日，时隔148天，我们再次相见，人行道上，你对我伸出小手，那是我第一次拉你的手，软软的，有点凉",
                lon: 112.906496,
                lat: 29.847302,
            },
        ],
    },
    {
        name: "wuhan",
        text: "武汉",
        lon: 114.260073,
        lat: 30.446246,
        children: [
            {
                name: "xiangshuiwan",
                text: "香水湾",
                descript: "不能说是我们在武汉的家，仿佛有种陌生感，住的越久，越陌生",
                lon: 114.260073,
                lat: 30.446246,
            },
            {
                name: "hkRiverBeach",
                text: "汉口江滩",
                descript: "妹妹是不喜欢走动的，江滩却去了两次， 大武汉的灯光不输上海吧，那次意外地走错，却欣赏了不一样的风景",
                lon: 114.31124,
                lat: 30.598637,
            },
            {
                name: "wansongyuan",
                text: "万松园",
                descript: "我对武汉印象一直不太好，万松园是个例外，每次都想带你去尝尝不一样的，可惜你来的次数太少，还是老样子比较稳妥，老街烧烤来一套",
                lon: 114.267976,
                lat: 30.592581,
            },
            {
                name: "jinronggang",
                text: "金融港",
                descript: "你来的不多，我都记得，跟你一起下班是多么美好",
                lon: 114.425296,
                lat: 30.456019,
            },
        ],
    },
];
const category = {
    luxunPark: {
        name: "luxunPark",
        text: "鲁迅公园",
        imgList: [],
        videoLsit: [],
    },
};
